version: '3.1'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: ${MONGO_CONTAINER_NAME}
    ports:
      - ${MONGO_LOCALHOST_PORT}:27017
  backend:
    build: .
    command: python main.py
    volumes:
    - .:/app
    ports:
    - ${MAIN_BACKEND_SERVER_PORT}:${MAIN_BACKEND_SERVER_PORT}
    depends_on:
      - db
    container_name: ${MAIN_BACKEND_CONTAINER_NAME}
