version: '3.1'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    container_name: inpoint_mongodb
    ports:
      - ${MONGO_PORT}:27017
  backend:
    build: .
    command: python main.py
    volumes:
    - .:/app
    ports:
    - ${MAIN_BACKEND_SERVER_PORT}:8000
    depends_on:
      - db
    container_name: inpoint_main_backend