version: '3.1'

services:
  ai_db:
    image: neo4j:4.2.3
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_INITDB_ROOT_PASSWORD}
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      NEO4J_dbms_memory_heap_max__size: '${NEO4J_MAX_HEAP_SIZE}'
      NEO4J_dbms_memory_heap_initial__size: '${NEO4J_INITIAL_HEAP_SIZE}'
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,gds.*'
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
    container_name: ${NEO4J_CONTAINER_NAME}
    ports:
      - ${NEO4J_HTTP_PORT}:7474
      - ${NEO4J_BOLT_PORT}:7687
  ai_backend:
    build: .
    command: python main.py
    volumes:
    - .:/app
    ports:
    - ${AI_BACKEND_SERVER_PORT}:${AI_BACKEND_SERVER_PORT}
    depends_on:
      - ai_db
    container_name: ${AI_BACKEND_CONTAINER_NAME}
    network_mode: '${AI_BACKEND_NETWORK_MODE}'
